
title: My Resume
url: ''
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Anoob Prakash  ## put your name
title: 'UVM PhD student &amp; NSF QuEST intern'  ## your title
location: Burlington , VT


## Social Profiles
research gate: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url




# Update all the sections by editing the files inside _includes folder.
